//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordenDetalle
    {
        public int idDetalle { get; set; }
        public int nroOrden { get; set; }
        public int idProducto { get; set; }
        public int precioProducto { get; set; }
        public int cantidad { get; set; }
        public int subTotal { get; set; }
    }
}
