//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordenCompra
    {
        public int numOrden { get; set; }
        public string rutCliente { get; set; }
        public System.DateTime fecha { get; set; }
        public int neto { get; set; }
        public int usuario { get; set; }
    }
}
